version: '3'
services:
  java-service1:
    image: demo
    environment:
      - SERVER_PORT=8081
    ports:
      - "8081" # 將宿主機的 8081 映射到容器的 8080
    networks:
      - demo-network
  java-service2:
    image: demo
    environment:
      - SERVER_PORT=8082
    ports:
      - "8082" # 將宿主機的 8081 映射到容器的 8080
    networks:
      - demo-network
  nginx:
    image: nginx:latest
    depends_on:
      - java-service1
      - java-service2
    ports:
      - "8080:80"
    networks:
      - demo-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
networks:
  demo-network:
    driver: bridge